name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      additional-setup:
        required: false
        type: string

jobs:
  run:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Additional Setup (if specified)
        if: ${{ inputs.additional-setup != '' }}
        run: ${{ inputs.additional-setup }}

      - name: Run Tests (Native Only)
        run: cargo test -v
